# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Klausur

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  maven_package_cache: ".m2/repository/"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_package_cache"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      with:
       path: $maven_package_cache
       key: ${{runner.os}}-build
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn compile
  test:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
       path: $maven_package_cache
       key: ${{runner.os}}-build
    - name: Build with Maven
      run: mvn test
      
  package:
    runs-on: ubuntu-latest
    needs:
    - test
    - build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
       path: $maven_package_cache
       key: ${{runner.os}}-build
    - name: Build with Maven
      run: mvn package
    - uses: actions/upload-artifact@v2
      with: 
        name: artifact-${{ github.job }}-${{ github.sha }}
        path: target/*.jar

